# Generated by Django 4.2.7 on 2023-12-01 06:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbstractEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConnectionSettings",
            fields=[
                (
                    "abstractentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractentity",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField()),
                (
                    "protocol",
                    models.CharField(
                        choices=[("HTTP", "http"), ("MQTT", "mqtt"), ("AMQP", "amqp")],
                        max_length=20,
                    ),
                ),
            ],
            bases=("core.abstractentity",),
        ),
        migrations.CreateModel(
            name="HistoryAware",
            fields=[
                (
                    "abstractentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractentity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logs", models.JSONField(blank=True, null=True)),
            ],
            bases=("core.abstractentity",),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "abstractentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractentity",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            bases=("core.abstractentity",),
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "abstractentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractentity",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("settings", models.JSONField()),
            ],
            bases=("core.abstractentity",),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "historyaware_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.historyaware",
                    ),
                ),
                ("headers", models.JSONField()),
            ],
            bases=("core.historyaware",),
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "abstractentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractentity",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_integrations",
                        to="core.partner",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_integrations",
                        to="core.partner",
                    ),
                ),
            ],
            bases=("core.abstractentity",),
        ),
        migrations.CreateModel(
            name="GatewaySettings",
            fields=[
                (
                    "abstractentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractentity",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("settings", models.JSONField()),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.connectionsettings",
                    ),
                ),
                (
                    "gateway_integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gatewaysettings",
                        to="core.integration",
                    ),
                ),
            ],
            bases=("core.abstractentity",),
        ),
        migrations.AddField(
            model_name="connectionsettings",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.partner"
            ),
        ),
        migrations.CreateModel(
            name="MessageBody",
            fields=[
                (
                    "abstractentity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.abstractentity",
                    ),
                ),
                ("body", models.BinaryField()),
                ("timestamp", models.DateTimeField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.message"
                    ),
                ),
            ],
            bases=("core.abstractentity",),
        ),
        migrations.AddField(
            model_name="message",
            name="message_integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="core.integration",
            ),
        ),
    ]
