# Generated by Django 4.2.7 on 2023-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transactiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebody',
            name='content_type',
            field=models.CharField(default='application/json', max_length=255),
            preserve_default=False,
        ),
    ]
